version: '3.8'

services:
  webhook-handler:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PINNACLE_AI_WEBHOOK_URL=${PINNACLE_AI_WEBHOOK_URL}
      - FREE_ECOMMERCE_WEBHOOK_URL=${FREE_ECOMMERCE_WEBHOOK_URL}
      - PINNACLE_AI_WEBHOOK_SECRET=${PINNACLE_AI_WEBHOOK_SECRET}
      - FREE_ECOMMERCE_WEBHOOK_SECRET=${FREE_ECOMMERCE_WEBHOOK_SECRET}
      - SENTRY_DSN=${SENTRY_DSN}
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  redis_data: